export const local = {
  salaryArmen: "Salary Armen",
  salaryNastya: "Salary Nastya",
  titleGeneral: "General",
  titleCalculate: "Calculate",
  firstDayCalculate: "First Day",
  lastDayCalculate: "Last Day",
  categoriesForCalculate: "Target categories",
  products: "Products",
  health: "Health",
  services: "Services",
  communalApartment: "Communal",
  targetFirstDay: "Target First Day",
  targetLastDay: "Target Last Day",
  rent: "Rent",
  investmentRatio: "Investment ratio (%)",
  result: "Result",
  investment: "Investment",
  sum: "Sum",
};
